[build]
  base = "./"
  command = "make build"
  publish = "./site/"
  functions = "./functions/"
[build.environment]
  GO_IMPORT_PATH = "github.com/mlocher/stwa"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
