[build]
  base = "./"
  command = "npm run build"
  publish = "./dist/"
  functions = "./functions/dist/"

[build.environment]
  GO_IMPORT_PATH = "github.com/mlocher/stwa"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
